### ISSUE TITLE
Multiline Comments

### ISSUE THREAD

**Issue by sabriozgur** [hoheinzollern/language-tamarin#2]
One line comments ( "//" ) look gray as expected but multiline comments (/* */) are detected as code since they look red as if they are also part of the code.
Not sure this is intended or bug, but I will count this as a bug.

**Comment by hoheinzollern** [comment]
It is in fact an issue: Tamarin supports multiline comments:
https://github.com/tamarin-prover/tamarin-prover/tree/develop/etc
In fact, I should align the syntax to the referenced files.

**Comment by hoheinzollern** [comment]
Fixed, now they are included.
